"""
Module: get_time_range.py

Description:
Extracts the start and end timestamps for a specific satellite PRN from a dictionary
of satellite observation DataFrames. Assumes input data is generated by the read_rinex module.

Author: F.Ahmadzade
"""

from typing import Dict, Tuple
import pandas as pd
from warnings import warn

def get_time_range(sat_data_dict: Dict[str, pd.DataFrame], 
                  prn: str, 
                  time_col: str = 'time') -> Tuple[pd.Timestamp, pd.Timestamp]:
    """
    Extracting the time interval of satellite observations from RINEX data
    
    Args:
        sat_data_dict: Dict[PRN, DataFrame] from read_rinex
        prn: 'G05', 'R12', etc.
        time_col: time column name (default: 'time')
    
    Returns:
        (start_time, end_time)
    
    Raises:
        KeyError: PRN not found
        ValueError: Empty data or no time column
    """
    if prn not in sat_data_dict:
        raise KeyError(f"PRN '{prn}' not found in {list(sat_data_dict.keys())}")
    
    df = sat_data_dict[prn]
    if df.empty:
        raise ValueError(f"Empty DataFrame for PRN '{prn}'")
    
    if time_col not in df.columns:
        raise ValueError(f"Time column '{time_col}' not in DataFrame columns")
    
    # GNSS-specific: ensure Timestamp format
    time_series = pd.to_datetime(df[time_col])
    start_time = time_series.min()
    end_time = time_series.max()
    
    duration = (end_time - start_time).total_seconds() / 3600
    if duration > 48:
        warn(f"⚠️ Long session {duration:.1f}h for {prn} - check data validity")
    
    print(f"✓ {prn}: {len(df)} epochs, {duration:.1f}h ({start_time} → {end_time})")
    
    return start_time, end_time

# Real-world GNSS test
if __name__ == "__main__":
    mock_rinex = {
        'G05': pd.DataFrame({
            'time': pd.date_range('2026-02-13 09:00', periods=7200, freq='30S'),  # 24hr
            'L1': np.random.randn(7200), 'L2': np.random.randn(7200)
        })
    }
    
    start, end = get_time_range(mock_rinex, 'G05')
    print(f"✅ Result: {start} → {end} ({(end-start).total_seconds()/3600:.1f}h)")
