"""
Module: get_time_range.py

Description:
Extracts the start and end timestamps for a specific satellite PRN from a dictionary
of satellite observation DataFrames. Assumes input data is generated by the read_rinex module.

Author: F.Ahmadzade
"""

from typing import Dict, Tuple
import pandas as pd

def get_time_range(sat_data_dict: Dict[str, pd.DataFrame], prn: str) -> Tuple[pd.Timestamp, pd.Timestamp]:
    """
    Get the start and end times for a given satellite PRN from observation data.

    Args:
        sat_data_dict (Dict[str, pd.DataFrame]): Dictionary mapping satellite IDs to their observation DataFrames.
        prn (str): Satellite identifier (e.g. 'G05' or 'R12').

    Returns:
        Tuple[pd.Timestamp, pd.Timestamp]: Start and end timestamps of observations.

    Raises:
        KeyError: If the specified PRN is not found in the data dictionary.
        ValueError: If the DataFrame for the PRN is empty.
    """
    if prn not in sat_data_dict:
        raise KeyError(f"Satellite PRN '{prn}' not found in the observation data.")

    df = sat_data_dict[prn]
    if df.empty:
        raise ValueError(f"No observation data available for satellite PRN '{prn}'.")

    start_time = df['time'].min()
    end_time = df['time'].max()
    return start_time, end_time


if __name__ == "__main__":
    # Example usage (replace sat_dict with actual output from read_rinex)
    import pandas as pd
    from datetime import datetime

    # Mock example for testing
    mock_data = {
        'G05': pd.DataFrame({
            'time': pd.date_range(start='2025-11-24 00:00:00', periods=5, freq='30S'),
            'L1': [1, 2, 3, 4, 5],
            'L2': [1, 2, 3, 4, 5],
            'C1': [1, 2, 3, 4, 5],
            'C2': [1, 2, 3, 4, 5],
        })
    }
    start, end = get_time_range(mock_data, 'G05')
    print(f"Start time: {start}, End time: {end}")